### ISSUE TITLE
[Suggestion] malloc_trim compatibility issues

### ISSUE THREAD

**Issue by CalebHeydon** [pop-os/cosmic-bg#47]
Is malloc_trim necessary in main.rs? It's not compatible with alternative libc implementations like musl.

**Comment by Drakulix** [comment]
Not that is merely an optimization. Would you consider opening a PR, that makes this optional?

**Comment by CalebHeydon** [comment]
I don't know much rust. How would you recommend doing it?

**Comment by joshuamegnauth54** [comment]
You can try gating the `libc` specific code with [cfg](https://doc.rust-lang.org/rust-by-example/attribute/cfg.html). You'll likely need to use the [target_env](https://doc.rust-lang.org/reference/conditional-compilation.html) attribute with `cfg`.

```rust
#[cfg(target_env = "gnu")]
fn some_optimized_code() {
    println!("Calling libc specific code");
}

#[cfg(not(target_env = "gnu"))]
fn some_optimized_code() {
    println!("Calling portable version");
}

fn main() {
    some_optimized_code()
}
```
